version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: basvastaxi_user
      POSTGRES_PASSWORD: basvastaxi_password
      POSTGRES_DB: basvastaxi_sql
      POSTGRES_MAX_CONNECTIONS: 1000
    ports:
      - "5432:5432"
    working_dir: /var/lib/postgresql/data
    volumes:
      - Postgres:/var/lib/postgresql/data


volumes:
  Postgres: